# PyTorch Basics<br>
By Kenneth Lim

Given with this simple pipeline, we will try out how PyTorch works with this simple academic activity from my Deep Learning Class.

1. Perform Standard Imports

In [5]:
import torch
import numpy as np
import sys
import random

2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

In [30]:
def set_seed(seed:int):
    torch.manual_seed(seed)
    return None

3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.

In [31]:
arr = np.array([0,2,4,3,1,3])
set_seed(42)

4. Create a tensor "x" from the array above

In [32]:
x = torch.from_numpy(arr)

5. Change the dtype of x from int32 to int64

In [33]:
x = x.type(torch.int64)

6. Reshape x into a 3x2 tensor \
*There are several ways to do this*

In [34]:
x = x.view(3,2)
x

tensor([[0, 2],
        [4, 3],
        [1, 3]])

7. Return the right-hand column of tensor x

In [35]:
x[:,1]

tensor([2, 3, 3])

8. Without changing x, return a tensor of square values of x \
*There are several ways to do this.*

In [36]:
x_squared = x ** 2
x_squared

tensor([[ 0,  4],
        [16,  9],
        [ 1,  9]])

9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x \
   *Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.*

In [40]:
set_seed(42)
y = torch.randint(0,5,(2,3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])


10. Find the matrix product of x and y.

In [38]:
torch.matmul(x,y)

tensor([[ 8,  2,  0],
        [20, 11,  4],
        [14,  5,  1]])

In [29]:
torch.mm(x,y)

tensor([[ 8,  2,  0],
        [20, 11,  4],
        [14,  5,  1]])

So there we go! From simple data transformations and conversions that gives you the best essentials on dealing with some deep learning projects.